services:
  - type: web
    name: sistema-credito
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker backend.app.main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11