export enum CommercialStage {
  RESERVA = 'RESERVA',
  EM_PROCESSO = 'EM_PROCESSO',
  CREDITO = 'CREDITO',
  SECRETARIA_VENDAS = 'SECRETARIA_VENDAS',
  ASSINATURA_DIRETORIA = 'ASSINATURA_DIRETORIA',
  AUTORIZACAO_DIRETORIA = 'AUTORIZACAO_DIRETORIA',
  ENVIO_SIENGE = 'ENVIO_SIENGE',
  VENDA_FINALIZADA = 'VENDA_FINALIZADA',
}

export enum TransferStage {
  EM_REPASSE = 'EM_REPASSE',
  INICIO_REPASSE = 'INICIO_REPASSE',
  ASSINATURA_AUTORIZADA = 'ASSINATURA_AUTORIZADA',
}

export enum GeneralStatus {
  NOVO = 'NOVO',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  PENDENCIADO = 'PENDENCIADO',
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
  DISTRATO = 'DISTRATO',
  CANCELADO = 'CANCELADO',
}

export enum CaixaStatus {
  ANALISE_CREDITO = 'ANALISE_CREDITO',
  PENDENTE_CREDITO = 'PENDENTE_CREDITO',
  ANALISE_CCA = 'ANALISE_CCA',
  PENDENTE_CCA = 'PENDENTE_CCA',
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
  CONDICIONADO = 'CONDICIONADO',
  BLOQUEADO = 'BLOQUEADO',
  DAR_QV = 'DAR_QV',
  AGUARDANDO_CONFORMIDADE = 'AGUARDANDO_CONFORMIDADE',
  CONFORME = 'CONFORME',
  TRATANDO_PRODUTO = 'TRATANDO_PRODUTO',
  AGENDADO = 'AGENDADO',
  ASSINATURA_CAIXA = 'ASSINATURA_CAIXA',
  FINALIZADO = 'FINALIZADO',
}

export enum AgehabStatus {
  ANALISE_CREDITO = 'ANALISE_CREDITO',
  PENDENTE_CREDITO = 'PENDENTE_CREDITO',
  ENVIO_AGEHAB = 'ENVIO_AGEHAB',
  PENDENTE_AGEHAB = 'PENDENTE_AGEHAB',
  VALIDADO_AGEHAB = 'VALIDADO_AGEHAB',
}

export enum BinaryOperationalStatus {
  NAO_TEM = 'NAO_TEM',
  PENDENTE = 'PENDENTE',
  PAGO = 'PAGO',
  APROVADO = 'APROVADO',
  FINALIZADO = 'FINALIZADO',
}

export enum CurrentQueue {
  COMERCIAL = 'COMERCIAL',
  REPASSE = 'REPASSE',
}
