from app import (
    CHECKLIST_PAGE_ROLES,
    PROCESSO_DOCUMENTOS_UPSERT_ROLES,
    PROCESSO_FULL_ROLES,
    PROCESSO_INTAKE_ROLES,
    ROLE_CORRETOR,
)


def test_corretor_can_enter_checklist_flow_again():
    assert ROLE_CORRETOR in CHECKLIST_PAGE_ROLES
    assert ROLE_CORRETOR in PROCESSO_FULL_ROLES
    assert ROLE_CORRETOR in PROCESSO_INTAKE_ROLES
    assert ROLE_CORRETOR in PROCESSO_DOCUMENTOS_UPSERT_ROLES
