export enum DocumentStatus {
  PENDENTE = 'PENDENTE',
  ENVIADO = 'ENVIADO',
  APROVADO = 'APROVADO',
  NAO_APLICA = 'NAO_APLICA',
}

export enum DocumentCreditStatus {
  AGUARDANDO_ENVIO = 'AGUARDANDO_ENVIO',
  ANALISE = 'ANALISE',
  PENDENCIADO = 'PENDENCIADO',
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
  NAO_APLICA = 'NAO_APLICA',
}
